# Generated by Django 4.1.7 on 2023-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='nombre')),
                ('edad', models.IntegerField(null=True, verbose_name='edad')),
                ('genero', models.CharField(max_length=10, verbose_name='genero')),
                ('foto', models.ImageField(null=True, upload_to='img/', verbose_name='foto')),
            ],
        ),
    ]
